/**
 * Utilidad de resolución de banderas de países para peleadores y gimnasios de la UFC.
 * Soporta nombres en inglés, español, códigos ISO alpha-2, alpha-3 y fallbacks inteligentes.
 */

const COUNTRY_NAME_TO_ISO: Record<string, string> = {
  // Principales potencias de MMA
  'united states': 'us',
  'united states of america': 'us',
  'estados unidos': 'us',
  'usa': 'us',
  'brazil': 'br',
  'brasil': 'br',
  'france': 'fr',
  'francia': 'fr',
  'russia': 'ru',
  'rusia': 'ru',
  'mexico': 'mx',
  'méxico': 'mx',
  'spain': 'es',
  'españa': 'es',
  'new zealand': 'nz',
  'nueva zelanda': 'nz',
  'australia': 'au',
  'georgia': 'ge',
  'poland': 'pl',
  'polonia': 'pl',
  'england': 'gb',
  'inglaterra': 'gb',
  'united kingdom': 'gb',
  'reino unido': 'gb',
  'great britain': 'gb',
  'wales': 'gb-wls',
  'scotland': 'gb-sct',
  'ireland': 'ie',
  'irlanda': 'ie',
  'argentina': 'ar',
  'lithuania': 'lt',
  'lituania': 'lt',
  'portugal': 'pt',
  'canada': 'ca',
  'canadá': 'ca',
  'germany': 'de',
  'alemania': 'de',
  'italy': 'it',
  'italia': 'it',
  'japan': 'jp',
  'japón': 'jp',
  'south korea': 'kr',
  'korea': 'kr',
  'corea': 'kr',
  'china': 'cn',
  'kazakhstan': 'kz',
  'kazajistán': 'kz',
  'uzbekistan': 'uz',
  'uzbekistán': 'uz',
  'tajikistan': 'tj',
  'kyrgyzstan': 'kg',
  'armenia': 'am',
  'azerbaijan': 'az',
  'ecuador': 'ec',
  'colombia': 'co',
  'chile': 'cl',
  'peru': 'pe',
  'perú': 'pe',
  'venezuela': 've',
  'cuba': 'cu',
  'dominican republic': 'do',
  'república dominicana': 'do',
  'jamaica': 'jm',
  'south africa': 'za',
  'sudáfrica': 'za',
  'nigeria': 'ng',
  'cameroon': 'cm',
  'camerún': 'cm',
  'sweden': 'se',
  'suecia': 'se',
  'norway': 'no',
  'noruega': 'no',
  'denmark': 'dk',
  'dinamarca': 'dk',
  'finland': 'fi',
  'finlandia': 'fi',
  'netherlands': 'nl',
  'holanda': 'nl',
  'países bajos': 'nl',
  'belgium': 'be',
  'bélgica': 'be',
  'switzerland': 'ch',
  'suiza': 'ch',
  'austria': 'at',
  'czech republic': 'cz',
  'chequia': 'cz',
  'croatia': 'hr',
  'croacia': 'hr',
  'serbia': 'rs',
  'ukraine': 'ua',
  'ucrania': 'ua',
  'morocco': 'ma',
  'marruecos': 'ma',
  'turkey': 'tr',
  'turquía': 'tr',
  'philippines': 'ph',
  'filipinas': 'ph',
  'thailand': 'th',
  'tailandia': 'th',
  'egypt': 'eg',
  'egipto': 'eg',
  'greece': 'gr',
  'grecia': 'gr',
  'israel': 'il',
  'india': 'in',
  'iran': 'ir',
  'irak': 'iq',
  'iraq': 'iq',
  'hungary': 'hu',
  'hungría': 'hu',
  'romania': 'ro',
  'rumania': 'ro',
  'bulgaria': 'bg',
  'slovakia': 'sk',
  'eslovaquia': 'sk',
  'slovenia': 'si',
  'eslovenia': 'si',
  'singapore': 'sg',
  'singapur': 'sg',
  'malaysia': 'my',
  'malasia': 'my',
  'indonesia': 'id',
  'uruguay': 'uy',
  'paraguay': 'py',
  'bolivia': 'bo',
  'panama': 'pa',
  'panamá': 'pa',
  'costa rica': 'cr',
  'guatemala': 'gt',
  'honduras': 'hn',
  'el salvador': 'sv',
  'nicaragua': 'ni',
  'puerto rico': 'pr',
  'senegal': 'sn',
  'ghana': 'gh',
  'kenya': 'ke',
  'congo': 'cg',
  'dr congo': 'cd',
  'angola': 'ao',
  'tunisia': 'tn',
  'túnez': 'tn',
  'algeria': 'dz',
  'argelia': 'dz',
  'moldova': 'md',
  'belarus': 'by',
  'bielorrusia': 'by',
  'estonia': 'ee',
  'latvia': 'lv',
  'letonia': 'lv',
  'iceland': 'is',
  'islandia': 'is',
  'cyprus': 'cy',
  'chipre': 'cy',
  'united arab emirates': 'ae',
  'emiratos árabes': 'ae',
  'uae': 'ae',
  'qatar': 'qa',
  'saudi arabia': 'sa',
  'arabia saudita': 'sa',
  'bahrain': 'bh',
  'kuwait': 'kw',
  // Códigos ISO alpha-3 comunes de ESPN / COI
  'fra': 'fr',
  'bra': 'br',
  'arg': 'ar',
  'esp': 'es',
  'rus': 'ru',
  'mex': 'mx',
  'gbr': 'gb',
  'eng': 'gb',
  'irl': 'ie',
  'can': 'ca',
  'aus': 'au',
  'nzl': 'nz',
  'pol': 'pl',
  'ltu': 'lt',
  'prt': 'pt',
  'por': 'pt',
  'geo': 'ge',
  'kaz': 'kz',
  'uzb': 'uz',
  'tjk': 'tj',
  'kgz': 'kg',
  'arm': 'am',
  'aze': 'az',
  'zaf': 'za',
  'rsa': 'za',
  'nga': 'ng',
  'cmr': 'cm',
  'chn': 'cn',
  'jpn': 'jp',
  'kor': 'kr',
  'swe': 'se',
  'nor': 'no',
  'fin': 'fi',
  'dnk': 'dk',
  'nld': 'nl',
  'ned': 'nl',
  'bel': 'be',
  'che': 'ch',
  'sui': 'ch',
  'aut': 'at',
  'cze': 'cz',
  'hrv': 'hr',
  'cro': 'hr',
  'srb': 'rs',
  'ukr': 'ua',
  'mar': 'ma',
  'tur': 'tr',
  'phl': 'ph',
  'tha': 'th',
  'col': 'co',
  'ecu': 'ec',
  'chl': 'cl',
  'per': 'pe',
  'ven': 've',
  'cub': 'cu',
  'dom': 'do',
  'jam': 'jm',
  'are': 'ae',
};

// Fallback por nombres de peleadores conocidos si su país no viene especificado en la API
const FIGHTER_NAME_COUNTRY_MAP: Record<string, string> = {
  // Evento actual (Hooker vs Parnasse)
  'dan hooker': 'nz',
  'salahdine parnasse': 'fr',
  'benoît saint denis': 'fr',
  'benoit saint denis': 'fr',
  'morgan charriere': 'fr',
  'morgan charrière': 'fr',
  'felipe lima': 'br',
  'farés ziam': 'fr',
  'fares ziam': 'fr',
  'axel sola': 'fr',
  'michael page': 'gb',
  'nursulton ruziboev': 'uz',
  'punahele soriano': 'us',
  'daniil donchenko': 'ua',
  'trevor peek': 'us',
  'kurtis campbell': 'gb',
  'muhammad naimov': 'tj',
  'losene keita': 'be',
  'ryan spann': 'us',
  'mario pinto': 'pt',
  'modestas bukauskas': 'lt',
  'oumar sy': 'fr',
  'nathaniel wood': 'gb',
  'pavel andrusca': 'md',
  'michael aljarouj': 'fr',
  'fabia sintes': 'es',
  'nora cornolle': 'fr',
  'klaudia syguła': 'pl',
  'klaudia sygula': 'pl',
  'luis felipe dias': 'br',
  'matthieu letho duclos': 'fr',
  'sofia montenegro': 'ar',
  'delphine benouaich': 'fr',

  // UFC 308 (Topuria vs Holloway)
  'ilia topuria': 'es',
  'max holloway': 'us',
  'robert whittaker': 'au',
  'khamzat chimaev': 'ae',
  'magomed ankalaev': 'ru',
  'aleksandar rakic': 'at',
  'lerone murphy': 'gb',
  'dan ige': 'us',
  'shara magomedov': 'ru',
  'armen petrosyan': 'am',
  'ibo aslan': 'tr',
  'rafael cerqueira': 'br',
  'geoff neal': 'us',
  'rafael dos anjos': 'br',
  'mateusz rębecki': 'pl',
  'mateusz rebecki': 'pl',
  'myktybek orolbai': 'kg',
  'abus magomedov': 'de',
  'brunno ferreira': 'br',
  'kennedy nzechukwu': 'ng',
  'chris barnett': 'us',
  'farid basharat': 'gb',
  'victor hugo': 'br',
  'ismail naurdiev': 'at',
  'bruno silva': 'br',
  'rinat fakhretdinov': 'ru',
  'carlos leal': 'br',

  // Noche UFC 306 (O'Malley vs Dvalishvili)
  'sean o\'malley': 'us',
  'merab dvalishvili': 'ge',
  'alexa grasso': 'mx',
  'valentina shevchenko': 'kg',
  'brian ortega': 'mx',
  'diego lopes': 'br',
  'daniel zellhuber': 'mx',
  'esteban ribovics': 'ar',
  'ronaldo rodríguez': 'mx',
  'ronaldo rodriguez': 'mx',
  'ode\' osbourne': 'jm',
  'irene aldana': 'mx',
  'norma dumont': 'br',
  'manuel torres': 'mx',
  'ignacio bahamondes': 'cl',
  'yazmin jauregui': 'mx',
  'ketlen souza': 'br',
  'édgar cháirez': 'mx',
  'edgar chairez': 'mx',
  'joshua van': 'us',
  'raul rosas jr.': 'mx',
  'raul rosas jr': 'mx',
  'aoriqileng': 'cn',

  // UFC 300 (Pereira vs Hill)
  'alex pereira': 'br',
  'jamahal hill': 'us',
  'zhang weili': 'cn',
  'yan xiaonan': 'cn',
  'justin gaethje': 'us',
  'charles oliveira': 'br',
  'arman tsarukyan': 'am',
  'bo nickal': 'us',
  'cody brundage': 'us',
  'jiří procházka': 'cz',
  'jiri prochazka': 'cz',
  'aljamain sterling': 'us',
  'calvin kattar': 'us',
  'kayla harrison': 'us',
  'holly holm': 'us',
  'sodiq yusuff': 'ng',
  'jalin turner': 'us',
  'renato moicano': 'br',
  'jessica andrade': 'br',
  'marina rodriguez': 'br',
  'king green': 'us',
  'jim miller': 'us',
  'deiveson figueiredo': 'br',
  'cody garbrandt': 'us',

  // Leyendas adicionales
  'jon jones': 'us',
  'stipe miocic': 'us',
  'tom aspinall': 'gb',
  'alexander volkanovski': 'au',
  'dustin poirier': 'us',
  'shavkat rakhmonov': 'kz',
  'belal muhammad': 'us',
  'brandon moreno': 'mx',
  'alexandre pantoja': 'br',
  'leon edwards': 'gb',
  'islam makhachev': 'ru',
  'israel adesanya': 'nz',
  'dricus du plessis': 'za',
  'valter walker': 'br',
  'marcin tybura': 'pl',
  'mauricio ruffy': 'br',
  'gabriel santos': 'br',
};

/**
 * Normaliza y obtiene el código ISO alpha-2 para un país o peleador.
 */
export function resolveCountryCode(
  countryNameOrCode?: string | null,
  fighterName?: string | null
): string | null {
  // 1. Si viene un código o país explícito
  if (countryNameOrCode) {
    const clean = countryNameOrCode.trim().toLowerCase();
    
    // Si ya es un código de 2 letras (ej. 'fr', 'us', 'ar')
    if (clean.length === 2 && /^[a-z]{2}$/.test(clean)) {
      return clean;
    }

    // Si viene en el mapa de nombres
    if (COUNTRY_NAME_TO_ISO[clean]) {
      return COUNTRY_NAME_TO_ISO[clean];
    }
  }

  // 2. Si el país vino como 'Unknown' o vacío, intentar por nombre del peleador
  if (fighterName) {
    const cleanFighter = fighterName.trim().toLowerCase();
    if (FIGHTER_NAME_COUNTRY_MAP[cleanFighter]) {
      return FIGHTER_NAME_COUNTRY_MAP[cleanFighter];
    }
  }

  return null;
}

/**
 * Retorna la URL de la bandera en alta resolución (SVG o PNG).
 * Usa la CDN global de banderas FlagCDN con fallback a ESPN CDN.
 */
export function getCountryFlagUrl(
  countryNameOrCode?: string | null,
  fighterName?: string | null
): string | null {
  const code = resolveCountryCode(countryNameOrCode, fighterName);
  if (!code) return null;

  return `https://flagcdn.com/w320/${code}.png`;
}
